"""initial

Revision ID: 4e8652c45e8d
Revises: 
Create Date: 2025-06-06 19:02:29.672410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8652c45e8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('base_search_url', sa.String(), nullable=True),
    sa.Column('product_selector', sa.String(), nullable=True),
    sa.Column('title_selector', sa.String(), nullable=True),
    sa.Column('price_selector', sa.String(), nullable=True),
    sa.Column('link_selector', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketplaces_id'), 'marketplaces', ['id'], unique=False)
    op.create_table('scrape_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name_searched', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_requests_id'), 'scrape_requests', ['id'], unique=False)
    op.create_table('scraped_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_id', sa.Integer(), nullable=True),
    sa.Column('scraped_product_title', sa.String(), nullable=True),
    sa.Column('scraped_price', sa.String(), nullable=True),
    sa.Column('scraped_currency', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['scrape_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_products_id'), 'scraped_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_products_id'), table_name='scraped_products')
    op.drop_table('scraped_products')
    op.drop_index(op.f('ix_scrape_requests_id'), table_name='scrape_requests')
    op.drop_table('scrape_requests')
    op.drop_index(op.f('ix_marketplaces_id'), table_name='marketplaces')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
