"""initial

Revision ID: b7328873e442
Revises: 
Create Date: 2025-06-17 01:43:55.525828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7328873e442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_search_url', sa.String(), nullable=True),
    sa.Column('product_selector', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('additional_tag', sa.String(), nullable=True),
    sa.Column('title_selector', sa.String(), nullable=True),
    sa.Column('price_selector', sa.String(), nullable=True),
    sa.Column('link_selector', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description_selector', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_marketplaces_id'), 'marketplaces', ['id'], unique=False)
    op.create_table('scrape_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name_searched', sa.String(), nullable=False),
    sa.Column('requested_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_requests_id'), 'scrape_requests', ['id'], unique=False)
    op.create_table('scraped_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('scraped_product_title', sa.String(), nullable=False),
    sa.Column('scraped_price', sa.String(), nullable=False),
    sa.Column('scraped_currency', sa.String(), nullable=True),
    sa.Column('scraped_description', sa.JSON(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['scrape_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_products_id'), 'scraped_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_products_id'), table_name='scraped_products')
    op.drop_table('scraped_products')
    op.drop_index(op.f('ix_scrape_requests_id'), table_name='scrape_requests')
    op.drop_table('scrape_requests')
    op.drop_index(op.f('ix_marketplaces_id'), table_name='marketplaces')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
